//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parfumer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Articule { get; set; }
        public int Cost { get; set; }
        public int MaxSale { get; set; }
        public string Maker { get; set; }
        public string Provider { get; set; }
        public int Category_Id { get; set; }
        public int SaleNow { get; set; }
        public int Quantity { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
